<div class="container">

	<h1 align="center">SIMPLEST REST API</h1>

	<h3>This app show :</h3>
	<ul>
		<li><span class="alert alert-warning">POST <span class="link">/users</span></span> </li>
		<li><span class="alert alert-warning">GET <span class="link">/users/([0-9A-Za-z]+)</span> (Example: users/drkd2jr0aa1kv4lcbkrrbav9q6)</span> </li>
		<li><span class="alert alert-warning">GET <span class="link">/recent/([0-9A-Za-z]+)</span> (Example: recent/drkd2jr0aa1kv4lcbkrrbav9q6)</span> </li>
		<li><span class="alert alert-warning">PUT <span class="link">/users/([0-9A-Za-z]+)</span> (Example: users/drkd2jr0aa1kv4lcbkrrbav9q6)</span> </li>
		<li><span class="alert alert-warning">DELETE <span class="link">/users/([0-9A-Za-z]+)</span> (Example: users/drkd2jr0aa1kv4lcbkrrbav9q6)</span> </li>
		<li><span class="alert alert-warning">GET <span class="link">/recent/([0-9A-Za-z]+)/([0-9]+)</span> (Example: users/drkd2jr0aa1kv4lcbkrrbav9q6/1)</span> </li>
		<li><span class="alert alert-warning">DELETE <span class="link">/recent/([0-9A-Za-z]+)/([0-9]+)</span> (Example: users/drkd2jr0aa1kv4lcbkrrbav9q6/1)</span> </li>
	</ul>
</div>